### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/workfile_out.csv'

### ISSUE THREAD

**Issue by Nadedic** [dathere/covid19-time-series-utilities#27]
https://github.com/dathere/covid19-time-series-utilities/blob/902ff8ad1bbef4636b062555775101583a67dfb4/covid19-ingest.sh#L58

Happens here, how exactly can I trace if that csv makes it to my disk.

**Comment by jqnatividad** [comment]
Hi @Nadedic , what OS are you using?  Windows?  MacOS?

Anyway, you should try COVIDrefine instead as JHU sorts out it file format.  COVIDrefine uses the timeseries version of the JHU data and actually produces better data.

**Comment by Nadedic** [comment]
I am using Windows Subsystem Linux (WSL) I don't think windows would interfere with any thing there.
I moved ahead and ran refine shell but I will need to wait for geo-earch api key..

**Comment by abhi3232** [comment]
I am facing same issue. Is there any solution for this ?

**Comment by jqnatividad** [comment]
Hi @Nadedic @abhi3232 fixed it, so it should now work on MacOS and Windows...
